declare namespace NodeJS {
    interface ProcessEnv {
        EXPO_PUBLIC_APPWRITE_ENDPOINT: string;
        EXPO_PUBLIC_APPWRITE_PROJECT_ID: string;
        EXPO_PUBLIC_APPWRITE_PLATFORM_ID: string;
        EXPO_PUBLIC_APPWRITE_DATABASE_ID: string;
        EXPO_PUBLIC_APPWRITE_COLLECTION_ASSIGNMENTS_ID: string;
        EXPO_PUBLIC_APPWRITE_COLLECTION_SCOUTING_DATA_ID: string;
        EXPO_PUBLIC_APPWRITE_FUNCTION_VALIDATE_KEY_ID: string;
        EXPO_PUBLIC_APPWRITE_FUNCTION_SUBMIT_SCOUTING_ID: string;
    }
}

export {};
